version: '3.7'

# demo of the image

services:

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PHP_IMAGE: 24hoursmedia/pfpm74trift:1.0.4
    volumes:
      - ./src:/var/www/html
    environment:
      php_max_input_vars: 2000

