version: '3.7'

# demo of the image

services:

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      php_max_input_vars: 2000

